SELECT
  CLIENTE_ID,
  NOME,
  LOWER(EMAIL) AS EMAIL,
  CASE
    WHEN LENGTH(REGEXP_REPLACE(CELULAR, r'[^0-9]', '')) > 11
    THEN NULL
    ELSE REGEXP_REPLACE(CELULAR, r'[^0-9]', '')
  END AS CELULAR,
  SEXO,
  CAST(DATA_NASCIMENTO AS DATE) AS DATA_NASCIMENTO,
  INITCAP(CIDADE) AS CIDADE,
  ESTADO,
  REGEXP_REPLACE(CEP, r'[^0-9]', '') AS CEP,
  ENDERECO
FROM
  {{ source('raw', 'raw_clientes') }}