SELECT
  ITEM_ID,
  PEDIDO_ID,
  PRODUTO_ID,
  CAST(QUANTIDADE AS INT64) AS QUANTIDADE,
  CAST(VALOR_UNITARIO AS NUMERIC) AS VALOR_UNITARIO,
  CAST(SUBTOTAL AS NUMERIC) AS SUBTOTAL
FROM 
  {{ source('raw', 'raw_itens_pedido') }}