SELECT
  PEDIDO_ID,
  CLIENTE_ID,
  CAST(DATA_PEDIDO AS DATE) AS DATA_PEDIDO,
  FORMA_PAGAMENTO,
  STATUS,
  INITCAP(CANAL) AS CANAL,
  INITCAP(TRIM(ORIGEM)) AS ORIGEM,
  INITCAP(TRIM(TRANSPORTADORA)) AS TRANSPORTADORA,
  CAST(VALOR_TOTAL AS NUMERIC) AS VALOR_TOTAL
FROM
  {{ source('raw', 'raw_pedidos') }}