WITH
  PEDIDOS AS (
    SELECT
      COUNT(DISTINCT PEDIDO_ID) AS TOTAL_PEDIDOS,
      COUNT(DISTINCT CASE WHEN STATUS = 'Cancelado' THEN PEDIDO_ID END)
        AS PEDIDOS_CANCELADOS
    FROM {{ ref('fato_venda') }}
  )
SELECT
  TOTAL_PEDIDOS,
  PEDIDOS_CANCELADOS,
  ROUND(SAFE_DIVIDE(PEDIDOS_CANCELADOS, TOTAL_PEDIDOS) * 100, 2)
    AS TAXA_CANCELAMENTO
FROM PEDIDOS
