WITH
  RECEITA_YTD_ATUAL AS (
    SELECT SUM(SUBTOTAL) AS RECEITA_YTD_ATUAL
    FROM {{ ref('fato_venda') }}
    WHERE DATA >= DATE_TRUNC(CURRENT_DATE(), YEAR) AND DATA <= CURRENT_DATE() AND STATUS = 'Entregue'
  ),
  RECEITA_YTD_ANTERIOR AS (
    SELECT SUM(SUBTOTAL) AS RECEITA_YTD_ANTERIOR
    FROM {{ ref('fato_venda') }}
    WHERE
      DATA >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 1 YEAR), YEAR)
      AND DATA <= DATE_SUB(CURRENT_DATE(), INTERVAL 1 YEAR) AND STATUS = 'Entregue'
  )
SELECT
  A.RECEITA_YTD_ATUAL,
  P.RECEITA_YTD_ANTERIOR,
  ROUND(
    SAFE_DIVIDE(
      A.RECEITA_YTD_ATUAL - P.RECEITA_YTD_ANTERIOR,
      P.RECEITA_YTD_ANTERIOR)
      * 100,
    2) AS VARIACAO_PERCENTUAL
FROM RECEITA_YTD_ATUAL AS A
CROSS JOIN RECEITA_YTD_ANTERIOR AS P