WITH
  QTD_VENDAS_POR_CATEGORIA AS (
    SELECT
      P.CATEGORIA,
      SUM(FV.QUANTIDADE) AS QTD_VENDIDA,
      SUM(FV.SUBTOTAL) AS RECEITA
    FROM {{ ref('fato_venda') }} AS FV
    JOIN {{ ref('dim_produto') }} AS P
      ON FV.PRODUTO_ID = P.PRODUTO_ID
    WHERE FV.STATUS = 'Entregue'
    GROUP BY P.CATEGORIA
  )
SELECT
  CATEGORIA,
  QTD_VENDIDA,
  RECEITA
FROM QTD_VENDAS_POR_CATEGORIA
WHERE QTD_VENDIDA = (SELECT MAX(QTD_VENDIDA) FROM QTD_VENDAS_POR_CATEGORIA)