WITH
  RECEITA_MTD_ATUAL AS (
    SELECT SUM(SUBTOTAL) AS RECEITA_MTD_ATUAL
    FROM {{ ref('fato_venda') }}
    WHERE DATA >= DATE_TRUNC(CURRENT_DATE(), MONTH) AND DATA <= CURRENT_DATE() AND STATUS = 'Entregue'
  ),
  RECEITA_MTD_ANTERIOR AS (
    SELECT SUM(SUBTOTAL) AS RECEITA_MTD_ANTERIOR
    FROM {{ ref('fato_venda') }}
    WHERE
      DATA >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH), MONTH)
      AND DATA <= DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH) AND STATUS = 'Entregue'
  )
SELECT
  A.RECEITA_MTD_ATUAL,
  P.RECEITA_MTD_ANTERIOR,
  ROUND(
    SAFE_DIVIDE(
      A.RECEITA_MTD_ATUAL - P.RECEITA_MTD_ANTERIOR,
      P.RECEITA_MTD_ANTERIOR)
      * 100,
    2) AS VARIACAO_PERCENTUAL
FROM RECEITA_MTD_ATUAL AS A
CROSS JOIN RECEITA_MTD_ANTERIOR AS P
