WITH
  CLIENTES_ATIVOS AS (
    SELECT
      COUNT(DISTINCT CLIENTE_ID) AS TOTAL_CLIENTES_ATIVOS
    FROM {{ ref('rpt_clientes_ativos_90_dias') }}
  ),
  TOTAL_CLIENTES AS (
    SELECT
      COUNT(DISTINCT CLIENTE_ID) AS TOTAL_CLIENTES
    FROM {{ ref('dim_cliente') }}
  )
SELECT
  SAFE_DIVIDE(
    CLIENTES_ATIVOS.TOTAL_CLIENTES_ATIVOS, TOTAL_CLIENTES.TOTAL_CLIENTES)
    AS TAXA_CLIENTES_ATIVOS
FROM CLIENTES_ATIVOS
CROSS JOIN TOTAL_CLIENTES
