SELECT
  F.DATA,
  C.CLIENTE_ID,
  C.EMAIL,
  P.PRODUTO,
  P.CATEGORIA,
  F.QUANTIDADE,
  F.VALOR_UNITARIO,
  F.SUBTOTAL,
  F.CANAL,
  F.FORMA_PAGAMENTO
FROM {{ ref("fato_venda") }} AS FV
JOIN {{ ref("dim_cliente") }} AS C
  ON F.CLIENTE_ID = C.CLIENTE_ID
JOIN {{ ref("dim_produto") }} AS P
  ON F.PRODUTO_ID = P.PRODUTO_ID
WHERE F.DATA >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
ORDER BY F.DATA DESC