SELECT
  F.DATA,
  C.CLIENTE_ID,
  C.EMAIL,
  P.PRODUTO,
  P.CATEGORIA,
  F.QUANTIDADE,
  F.VALOR_UNITARIO,
  F.SUBTOTAL,
  F.CANAL,
  F.FORMA_PAGAMENTO
FROM {{ ref("fato_venda") }} AS F
JOIN {{ ref("dim_cliente") }} AS C
  ON F.CLIENTE_ID = C.CLIENTE_ID
JOIN {{ ref("dim_produto") }} AS P
  ON F.PRODUTO_ID = P.PRODUTO_ID
WHERE EXTRACT(YEAR FROM F.DATA) = EXTRACT(YEAR FROM CURRENT_DATE())
  AND EXTRACT(MONTH FROM F.DATA) = EXTRACT(MONTH FROM CURRENT_DATE())
ORDER BY
  F.DATA DESC,
  F.PEDIDO_ID