SELECT
    ORIGEM,
    COUNT(DISTINCT PEDIDO_ID) AS QUANTIDADE_PEDIDOS,
    SUM(QUANTIDADE) AS QUANTIDADE_PRODUTOS,
    ROUND(SUM(SUBTOTAL), 2) AS RECEITA
FROM {{ ref("fato_venda") }}
WHERE STATUS = "Entregue"
GROUP BY ORIGEM
ORDER BY RECEITA DESC