SELECT
  CLIENTE_ID,
  NOME,
  EMAIL,
  CELULAR,
  DATA_ULTIMO_PEDIDO,
  DIAS_DESDE_ULTIMA_COMPRA,
  QTD_TOTAL_PEDIDOS,
  VALOR_TOTAL_PEDIDOS
FROM {{ ref('dim_cliente') }}
WHERE DIAS_DESDE_ULTIMA_COMPRA <= 90
ORDER BY DIAS_DESDE_ULTIMA_COMPRA DESC