SELECT
  P.CATEGORIA,
  SUM(FV.QUANTIDADE) AS QTD_VENDIDA,
  SUM(FV.SUBTOTAL) AS RECEITA
FROM {{ ref('fato_venda') }} AS FV
JOIN {{ ref('dim_produto') }} AS P
  ON FV.PRODUTO_ID = P.PRODUTO_ID
WHERE FV.STATUS = "Entregue"
GROUP BY P.CATEGORIA
ORDER BY RECEITA DESC
