SELECT
  FV.DATA,
  C.CLIENTE_ID,
  C.EMAIL,
  P.PRODUTO,
  P.CATEGORIA,
  FV.QUANTIDADE,
  FV.VALOR_UNITARIO,
  FV.SUBTOTAL,
  FV.CANAL,
  FV.FORMA_PAGAMENTO
FROM {{ ref("fato_venda") }} AS FV
JOIN {{ ref("dim_cliente") }} AS C
  ON FV.CLIENTE_ID = C.CLIENTE_ID
JOIN {{ ref("dim_produto") }} AS P
  ON FV.PRODUTO_ID = P.PRODUTO_ID
WHERE FV.DATA >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
ORDER BY FV.DATA DESC