WITH CALENDARIO AS (
  SELECT DATA
  FROM UNNEST(
    GENERATE_DATE_ARRAY(
      DATE('2020-01-01'),
      DATE('2035-12-31'),
      INTERVAL 1 DAY
    )
  ) AS DATA
)

SELECT
  DATA AS DATA,
  EXTRACT(YEAR FROM DATA) AS ANO,
  EXTRACT(QUARTER FROM DATA) AS TRIMESTRE,
  EXTRACT(MONTH FROM DATA) AS MES,
  FORMAT_DATE('%B', DATA) AS NOME_MES,
  EXTRACT(DAY FROM DATA) AS DIA,
  EXTRACT(DAYOFWEEK FROM DATA) AS DIA_SEMANA
FROM CALENDARIO