SELECT
  C.CLIENTE_ID,
  C.NOME,
  C.EMAIL,
  C.CELULAR,
  C.SEXO,
  C.DATA_NASCIMENTO,
  C.CIDADE,
  C.ESTADO,
  C.CEP,
  C.ENDERECO,
  CM.DATA_PRIMEIRO_PEDIDO,
  CM.DATA_ULTIMO_PEDIDO,
  CM.QTD_TOTAL_PEDIDOS,
  CM.VALOR_TOTAL_PEDIDOS,
  CM.VALOR_MEDIO_PEDIDOS,
  CM.DIAS_DESDE_PRIMEIRA_COMPRA,
  CM.DIAS_DESDE_ULTIMA_COMPRA
FROM {{ ref('stg_clientes') }} AS C
LEFT JOIN {{ ref('int_cliente_metricas') }} AS CM
  ON C.CLIENTE_ID = CM.CLIENTE_ID