SELECT
  ITEM_ID,
  PEDIDO_ID,
  CLIENTE_ID,
  PRODUTO_ID,
  DATA_PEDIDO AS DATA,
  QUANTIDADE,
  VALOR_UNITARIO,
  SUBTOTAL,
  FORMA_PAGAMENTO,
  STATUS,
  CANAL,
  ORIGEM,
  TRANSPORTADORA
FROM {{ ref('int_itens_pedidos_detalhados') }}